language: node_js
node_js:
   - "4"
   - "6"
os:
  - linux
#before_script:
#  - cd grid-api; npm install
sudo: required
env:
  - NODE_ENV=test
services:
  - docker
script:
  - npm test && npm run testbehavior
